In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [33]:
df=pd.read_csv("wine.csv")

In [58]:
df.sample(5)

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
46      1    14.38        3.59  2.28  16.0  102     3.25        3.17   
85      2    12.67        0.98  2.24  18.0   99     2.20        1.94   
137     3    12.53        5.51  2.64  25.0   96     1.79        0.60   
131     3    12.88        2.99  2.40  20.0  104     1.30        1.22   
139     3    12.84        2.96  2.61  24.0  101     2.32        0.60   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
46                   0.27     2.19       4.90  1.04  3.44     1065  
85                   0.30     1.46       2.62  1.23  3.16      450  
137                  0.63     1.10       5.00  0.82  1.69      515  
131                  0.24     0.83       5.40  0.74  1.42      530  
139                  0.53     0.81       4.92  0.89  2.15      590

In [35]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=42)

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
from sklearn.decomposition import PCA

In [48]:
pca = PCA(n_components = 2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [49]:
pca.explained_variance_ratio_

array([0.3639525 , 0.18617733])

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
y_pred = model.predict(X_test)

In [54]:
y_pred

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 2, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1, 3, 3, 2, 3, 2, 2, 2, 2,
       3], dtype=int64)

In [55]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [56]:
cm

array([[13,  2,  0],
       [ 0, 18,  0],
       [ 0,  0, 12]], dtype=int64)